---
- hosts: webserver
  user: root
  connection: ssh
#  vars:
#    playbook_type: conditionalexample
#  vars_files:
#   - conf/copyright.yml
#  - conf/webdefaults.yml
  tasks:
    - name: install apache distribution type (RedHat/CentOS) 
      command: yum -y install apache2
      when: ansible_os_family == RedHat
