---
- hosts: webserver
  user: root
  sudo: yes
  connection: ssh
  tasks: 
   - name: add a list of users
     user: name={{ item }} state=present
     with_items:
       - user1
       - user2
       - user3
