---
- hosts: webserver
  user: root
  sudo: yes
  
  tasks:
  - name: install httpd on webserver
    action: yum name=httpd state=installed
  - name: pause and check installation
    pause:
      prompt: "check installation and continue further"

- hosts: all
  user: root
  tasks:
  - name: install lynx on all servers 
    yum: name=lynx state=installed
