---
- hosts: dbserver
  user: root
  sudo: yes

  tasks:
   - name: check for tomcat installation
     action: yum name=tomcat state=present
   - name: wait for port 8080 to listen
     wait_for:
       port: 8080
       state: started
   - name: verify lynx installation
     action: yum name=lynx state=present
